### ISSUE TITLE
运行 KAN-TTS 的 preprocess 时，出现 [ONNXRuntimeError] : 7 : INVALID_PROTOBUF ERROR !

### ISSUE THREAD

**Issue by wxbool** [alibaba-damo-academy/KAN-TTS#45]
运行 KAN-TTS 的 preprocess 脚本时，遇到了一个 ONNXRuntimeError，错误提示是在加载 se.onnx 模型时出现了 Protobuf 解析错误。

我参考的训练流程是这里的：https://www.modelscope.cn/models/damo/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/summary

![image](https://user-images.githubusercontent.com/29696787/228881510-f442e01d-8272-4abc-a2ef-73555a88454b.png)

运行的命令和结果输出如下：

```python kantts/preprocess/data_process.py --voice_input_dir /home/speech_personal_sambert_modelscope/KAN-TTS/resource/test_male_autolabel --voice_output_dir training_stage/test_male_ptts_feats --audio_config kantts/configs/audio_config_se_16k.yaml --speaker test_male --se_model speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/basemodel_16k/speaker_embedding/se.onnx ```

```
(maas) [root@VM-16-3-centos KAN-TTS]# python kantts/preprocess/data_process.py --voice_input_dir /home/speech_personal_sambert_modelscope/KAN-TTS/resource/test_male_autolabel --voice_output_dir training_stage/test_male_ptts_feats --audio_config kantts/configs/audio_config_se_16k.yaml --speaker test_male --se_model speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/basemodel_16k/speaker_embedding/se.onnx
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 13163.76it/s]
2023-03-30:23:02:36 INFO [TextScriptConvertor.py:469] TextScriptConvertor.process:
Save script to: training_stage/test_male_ptts_feats/Script.xml
2023-03-30:23:02:36 INFO [TextScriptConvertor.py:490] TextScriptConvertor.process:
Save metafile to: training_stage/test_male_ptts_feats/raw_metafile.txt
2023-03-30:23:02:36 INFO [audio_processor.py:90] [AudioProcessor] Initialize AudioProcessor.
2023-03-30:23:02:36 INFO [audio_processor.py:91] [AudioProcessor] config params:
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] wav_normalize: True
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] trim_silence: True
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] trim_silence_threshold_db: 60
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] preemphasize: False
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] sampling_rate: 16000
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] hop_length: 200
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] win_length: 1000
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] n_fft: 2048
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] n_mels: 80
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] fmin: 0.0
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] fmax: 8000.0
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] phone_level_feature: True
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] se_feature: True
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] norm_type: mean_std
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] max_norm: 1.0
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] symmetric: False
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] min_level_db: -100.0
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] ref_level_db: 20
2023-03-30:23:02:36 INFO [audio_processor.py:93] [AudioProcessor] num_workers: 16
2023-03-30:23:02:36 INFO [audio_processor.py:201] [AudioProcessor] Amplitude normalization started
2023-03-30:23:02:36 INFO [utils.py:184] Volume statistic proceeding...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 191.17it/s]
2023-03-30:23:02:36 INFO [utils.py:170] Average amplitude RMS : 0.054727649999999996
2023-03-30:23:02:36 INFO [utils.py:186] Volume statistic done.
2023-03-30:23:02:36 INFO [utils.py:194] Volume normalization proceeding...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 2199.60it/s]
2023-03-30:23:02:36 INFO [utils.py:221] Volume normalization done.
2023-03-30:23:02:36 INFO [audio_processor.py:204] [AudioProcessor] Amplitude normalization finished
2023-03-30:23:02:36 INFO [audio_processor.py:394] [AudioProcessor] Duration generation started
  0%|                                                                                                                                                                | 0/20 [00:00<?, ?it/s]2023-03-30:23:02:36 INFO [audio_processor.py:411] [AudioProcessor] Duration align with mel is proceeding...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 182.71it/s]
2023-03-30:23:02:36 INFO [audio_processor.py:453] [AudioProcessor] Duration generate finished
2023-03-30:23:02:36 INFO [audio_processor.py:278] [AudioProcessor] Trim silence with interval started
2023-03-30:23:02:36 INFO [audio_processor.py:216] [AudioProcessor] Start to load pcm from training_stage/test_male_ptts_feats/wav
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 179.38it/s]
  0%|                                                                                                                                                                | 0/20 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 4150.72it/s]
2023-03-30:23:02:37 INFO [audio_processor.py:314] [AudioProcessor] Trim silence finished
2023-03-30:23:02:37 INFO [audio_processor.py:322] [AudioProcessor] Melspec extraction started
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 56.95it/s]
2023-03-30:23:02:37 INFO [audio_processor.py:361] [AudioProcessor] Melspec extraction finished
2023-03-30:23:02:37 INFO [audio_processor.py:365] Melspec statistic proceeding...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 39107.73it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 10867.48it/s]
2023-03-30:23:02:37 INFO [audio_processor.py:368] Melspec statistic done
2023-03-30:23:02:37 INFO [audio_processor.py:374] [AudioProcessor] melspec mean and std saved to:
training_stage/test_male_ptts_feats/mel/mel_mean.txt,
training_stage/test_male_ptts_feats/mel/mel_std.txt
2023-03-30:23:02:37 INFO [audio_processor.py:378] [AudioProcessor] Melspec mean std norm is proceeding...
2023-03-30:23:02:37 INFO [audio_processor.py:384] [AudioProcessor] Melspec normalization finished
2023-03-30:23:02:37 INFO [audio_processor.py:385] [AudioProcessor] Normed Melspec saved to training_stage/test_male_ptts_feats/mel
2023-03-30:23:02:37 INFO [audio_processor.py:467] [AudioProcessor] Pitch extraction started
  0%|                                                                                                                                                                | 0/20 [00:00<?, ?it/s]2023-03-30:23:02:37 INFO [audio_processor.py:483] [AudioProcessor] Pitch align with mel is proceeding...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 73.88it/s]
2023-03-30:23:02:37 INFO [audio_processor.py:510] [AudioProcessor] Pitch normalization is proceeding...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 72565.81it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 33209.06it/s]
2023-03-30:23:02:37 INFO [audio_processor.py:518] [AudioProcessor] f0 mean and std saved to:
training_stage/test_male_ptts_feats/f0/f0_mean.txt,
training_stage/test_male_ptts_feats/f0/f0_std.txt
2023-03-30:23:02:37 INFO [audio_processor.py:521] [AudioProcessor] Pitch mean std norm is proceeding...
2023-03-30:23:02:37 INFO [audio_processor.py:548] [AudioProcessor] Pitch turn to phone-level is proceeding...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 182.40it/s]
2023-03-30:23:02:37 INFO [audio_processor.py:580] [AudioProcessor] Pitch normalization finished
2023-03-30:23:02:37 INFO [audio_processor.py:581] [AudioProcessor] Normed f0 saved to training_stage/test_male_ptts_feats/f0
2023-03-30:23:02:37 INFO [audio_processor.py:582] [AudioProcessor] Pitch extraction finished
2023-03-30:23:02:37 INFO [audio_processor.py:593] [AudioProcessor] Energy extraction started
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 116.35it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 59033.13it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 31968.78it/s]
2023-03-30:23:02:38 INFO [audio_processor.py:638] [AudioProcessor] energy mean and std saved to:
training_stage/test_male_ptts_feats/energy/energy_mean.txt,
training_stage/test_male_ptts_feats/energy/energy_std.txt
2023-03-30:23:02:38 INFO [audio_processor.py:642] [AudioProcessor] Energy mean std norm is proceeding...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 186.50it/s]
2023-03-30:23:02:38 INFO [audio_processor.py:690] [AudioProcessor] Energy normalization finished
2023-03-30:23:02:38 INFO [audio_processor.py:691] [AudioProcessor] Normed Energy saved to training_stage/test_male_ptts_feats/energy
2023-03-30:23:02:38 INFO [audio_processor.py:692] [AudioProcessor] Energy extraction finished
2023-03-30:23:02:38 INFO [audio_processor.py:774] [AudioProcessor] All features extracted successfully!
2023-03-30:23:02:38 INFO [data_process.py:192] Processing audio done.
2023-03-30:23:02:38 INFO [se_processor.py:63] [SpeakerEmbeddingProcessor] Speaker embedding extractor started
2023-03-30:23:02:38 ERROR [data_process.py:237] [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/basemodel_16k/speaker_embedding/se.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "kantts/preprocess/data_process.py", line 234, in <module>
    args.se_model,
  File "kantts/preprocess/data_process.py", line 199, in process_data
    se_model,
  File "/home/speech_personal_sambert_modelscope/KAN-TTS/kantts/preprocess/se_processor/se_processor.py", line 67, in process
    sess = onnxruntime.InferenceSession(se_onnx, sess_options=opts)
  File "/root/anaconda3/envs/maas/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/anaconda3/envs/maas/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/basemodel_16k/speaker_embedding/se.onnx failed:Protobuf parsing failed.
(maas) [root@VM-16-3-centos KAN-TTS]# 


```

**Comment by Alvinlyx** [comment]
需要安装git-lfs,，然后重新拉取 git clone https://www.modelscope.cn/damo/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k.git

**Comment by wxbool** [comment]
已解决，感谢

**Comment by fuxishuyuan** [comment]
请问一下最后怎么解决的？git-lfs安装之后还是报错
