### ISSUE TITLE
Gained a bug when modifying the speech rate （inference stage）

### ISSUE THREAD

**Issue by whalefa1I** [alibaba-damo-academy/KAN-TTS#46]
> 

1. The labeling standard will be released recently, and so will the automatic labeling service.
2. Sure, thanks for your feedback :)

_Originally posted by @GinChow in https://github.com/alibaba-damo-academy/KAN-TTS/issues/25#issuecomment-1340901510_

**Comment by whalefa1I** [comment]
```
class LengthRegulator(nn.Module):
    def __init__(self, r=1):
        super(LengthRegulator, self).__init__()

        self.r = r

    def forward(self, inputs, durations, masks=None):
        scale = 1.5
        # reps = (durations + 0.5).long()
        reps = (durations*scale + 0.5).long()
        output_lens = reps.sum(dim=1)
        max_len = output_lens.max()
        reps_cumsum = torch.cumsum(F.pad(reps.float(), (1, 0, 0, 0), value=0.0), dim=1)[
            :, None, :
        ]

```
errors like：
```
Traceback (most recent call last):
  File "kantts/bin/text_to_wav.py", line 176, in <module>
    args.lang,
  File "kantts/bin/text_to_wav.py", line 110, in text_to_wav
    am_infer(symbols_file, am_ckpt, output_dir, se_file)
  File "/opt/projects/KAN-TTS/kantts/bin/infer_sambert.py", line 218, in am_infer
    line[1], fsnet, ling_unit, device, se=se
  File "/opt/projects/KAN-TTS/kantts/bin/infer_sambert.py", line 121, in am_synthesis
    inputs_len,
  File "/opt/anaconda3/envs/maas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/projects/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 955, in forward
    energy_targets=energy_targets,
  File "/opt/anaconda3/envs/maas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/projects/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 490, in forward
    LR_text_outputs = LR_text_outputs + LR_position_embeddings
RuntimeError: The size of tensor a (915) must match the size of tensor b (609) at non-singleton dimension 1

```

**Comment by GinChow** [comment]
Multiply scale parameter in the following area:
https://github.com/alibaba-damo-academy/KAN-TTS/blob/f880fe4780bb8b2c7e88bc85df698f6f799382ac/kantts/models/sambert/kantts_sambert.py#L475-L488
after modification:
```python
 else: 
     scale = 1.5
     duration_predictions = duration_predictions * scale
     LR_text_outputs, LR_length_rounded = self.length_regulator( 
         inputs_text_embedding_aug, duration_predictions, masks=output_masks 
     ) 
     LR_position_embeddings = self.dur_position_encoder( 
         duration_predictions, masks=output_masks 
     ) 
     LR_emo_outputs, _ = self.length_regulator( 
         inputs_emo_embedding, duration_predictions, masks=output_masks 
     ) 
     LR_spk_outputs, _ = self.length_regulator( 
         inputs_spk_embedding, duration_predictions, masks=output_masks 
     ) 
```
