### ISSUE TITLE
run WuuShanghai and Cantonese error in KAN-TTS

### ISSUE THREAD

**Issue by YangangCao** [alibaba-damo-academy/KAN-TTS#49]
run WuuShanghai in basemodel_16k directory in KAN-TTS:
Traceback (most recent call last):
  File "kantts/bin/text_to_wav.py", line 218, in <module>
    text_to_wav(
  File "kantts/bin/text_to_wav.py", line 157, in text_to_wav
    am_infer(symbols_file, am_ckpt, output_dir, se_file)
  File "/data2/caoyangang/open_project/KAN-TTS/kantts/bin/infer_sambert.py", line 217, in am_infer
    mel, mel_post, dur, f0, energy = am_synthesis(
  File "/data2/caoyangang/open_project/KAN-TTS/kantts/bin/infer_sambert.py", line 83, in am_synthesis
    inputs_ling = torch.stack(
RuntimeError: stack expects each tensor to be equal size, but got [16] at entry 0 and [78] at entry 1

run WuuShanghai in voices directory in KAN-TTS get the same error as above

but run WuuShanghai in Modelscope is fine.

run Cantonese model in basemodel_16k directory in KAN-TTS:
Traceback (most recent call last):
  File "kantts/bin/text_to_wav.py", line 218, in <module>
    text_to_wav(
  File "kantts/bin/text_to_wav.py", line 157, in text_to_wav
    am_infer(symbols_file, am_ckpt, output_dir, se_file)
  File "/data2/caoyangang/open_project/KAN-TTS/kantts/bin/infer_sambert.py", line 217, in am_infer
    mel, mel_post, dur, f0, energy = am_synthesis(
  File "/data2/caoyangang/open_project/KAN-TTS/kantts/bin/infer_sambert.py", line 83, in am_synthesis
    inputs_ling = torch.stack(
RuntimeError: stack expects each tensor to be equal size, but got [16] at entry 0 and [78] at entry 1

run Cantonese model in voices directory in KAN-TTS:
Traceback (most recent call last):
  File "kantts/bin/text_to_wav.py", line 218, in <module>
    text_to_wav(
  File "kantts/bin/text_to_wav.py", line 157, in text_to_wav
    am_infer(symbols_file, am_ckpt, output_dir, se_file)
  File "/data2/caoyangang/open_project/KAN-TTS/kantts/bin/infer_sambert.py", line 201, in am_infer
    fsnet.load_state_dict(state_dict["model"], strict=False)
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for KanTtsSAMBERT:
	size mismatch for text_encoder.sy_emb.weight: copying a param with shape torch.Size([107, 512]) from checkpoint, the shape in current model is torch.Size([147, 512]).
	size mismatch for text_encoder.tone_emb.weight: copying a param with shape torch.Size([14, 512]) from checkpoint, the shape in current model is torch.Size([10, 512]).

run  Cantonese in Modelscope:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 212, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 247, in _process_single
    out = self.forward(out, **forward_params)
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/pipelines/audio/text_to_speech_pipeline.py", line 38, in forward
    output_wav = self.model.forward(input, forward_params.get('voice'))
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 272, in forward
    audio = self.synthesis_one_sentences(voice, line[1])
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 192, in synthesis_one_sentences
    return self.voices[voice_name].forward(text)
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/models/audio/tts/voice.py", line 650, in forward
    self.load_am()
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/modelscope/models/audio/tts/voice.py", line 253, in load_am
    self.am.load_state_dict(state_dict['model'], strict=False)
  File "/home/eeodev/anaconda3/envs/kan-tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for KanTtsSAMBERT:
	size mismatch for text_encoder.sy_emb.weight: copying a param with shape torch.Size([107, 512]) from checkpoint, the shape in current model is torch.Size([147, 512]).
	size mismatch for text_encoder.tone_emb.weight: copying a param with shape torch.Size([14, 512]) from checkpoint, the shape in current model is torch.Size([10, 512]).

**Comment by plutols** [comment]
@YangangCao Have you solved it?

**Comment by YangangCao** [comment]
don’t kantts for a long time, :)---- Replied Message ***@***.***>Date02/12/2025 11:18 ***@***.***> CcYangang ***@***.***>***@***.***>SubjectRe: [modelscope/KAN-TTS] run WuuShanghai and Cantonese error in KAN-TTS or ModelScope (Issue #49)
@YangangCao Have you solved it?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/modelscope/KAN-TTS/issues/49#issuecomment-2652564555",
"url": "https://github.com/modelscope/KAN-TTS/issues/49#issuecomment-2652564555",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by YangangCao** [comment]
don’t use kantts for a long time, :)---- Replied Message ***@***.***>Date02/12/2025 11:18 ***@***.***> CcYangang ***@***.***>***@***.***>SubjectRe: [modelscope/KAN-TTS] run WuuShanghai and Cantonese error in KAN-TTS or ModelScope (Issue #49)
@YangangCao Have you solved it?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/modelscope/KAN-TTS/issues/49#issuecomment-2652564555",
"url": "https://github.com/modelscope/KAN-TTS/issues/49#issuecomment-2652564555",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
