### ISSUE TITLE
KeyError: 'test_male'

### ISSUE THREAD

**Issue by pyh007** [alibaba-damo-academy/KAN-TTS#56]
Original Traceback (most recent call last):
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/datasets/dataset.py", line 461, in __getitem__
    ling_data = self.ling_unit.encode_symbol_sequence(ling_txt)
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/utils/ling_unit/ling_unit.py", line 226, in encode_symbol_sequence
    lfeat_symbol_separate[index].strip(), self._lfeat_type_list[index]
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/utils/ling_unit/ling_unit.py", line 293, in encode_sub_unit
    sequence = self.encode_speaker_category(this_lfeat_symbol)
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/utils/ling_unit/ling_unit.py", line 393, in encode_speaker_category
    sequence.append(self._speaker_to_id[this_speaker])
KeyError: 'test_male'
Traceback (most recent call last):
  File "kantts/bin/train_sambert.py", line 190, in train
    trainer.train()
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/train/trainer.py", line 199, in train
    self.train_epoch()
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/train/trainer.py", line 206, in train_epoch
    for batch in tqdm(self.train_loader):
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/akira/anaconda3/envs/maas/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/datasets/dataset.py", line 461, in __getitem__
    ling_data = self.ling_unit.encode_symbol_sequence(ling_txt)
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/utils/ling_unit/ling_unit.py", line 226, in encode_symbol_sequence
    lfeat_symbol_separate[index].strip(), self._lfeat_type_list[index]
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/utils/ling_unit/ling_unit.py", line 293, in encode_sub_unit
    sequence = self.encode_speaker_category(this_lfeat_symbol)
  File "/home/akira/KAN-TTS-1/KAN-TTS/kantts/utils/ling_unit/ling_unit.py", line 393, in encode_speaker_category
    sequence.append(self._speaker_to_id[this_speaker])
KeyError: 'test_male'，这个问题有人遇见过吗，怎么解决

**Comment by LufeiTang** [comment]
请问解决了吗？我也遇到了这个问题，求助

**Comment by wswcy1835** [comment]
改错配置文件了吧，使用预训练模型微调应该改speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/basemodel_16k/sambert/config.yaml这个文件，改其中的speaker_list，我是这么解决的
